# Generated by Django 2.2.6 on 2020-11-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(max_length=255, upload_to='images')),
            ],
        ),
    ]
