# Generated by Django 2.2.6 on 2020-11-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20201126_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='my_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilephoto', to='demoapp.myprofile'),
        ),
    ]
