# Generated by Django 2.2.6 on 2020-11-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='firstname',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='myprofile',
            old_name='lastname',
            new_name='city',
        ),
    ]
