# Generated by Django 2.2.6 on 2020-12-04 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='e_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filterapp.event_user'),
        ),
    ]
