# Generated by Django 2.2.6 on 2020-11-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_student_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='rollno',
        ),
    ]
